services:
  flask_app:
    container_name: flask_app
    image: flask_live_app:latest
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    restart: always
  
  flask_db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: {}

